export const TURN_KETTLE_ON = "TURN_KETTLE_ON";
export const TURN_KETTLE_ON_SUCCESS = "TURN_KETTLE_ON_SUCCESS";
export const REGISTER_CONTROLLER = "REGISTER_CONTROLLER";
export const ALARM_TRIGGERED = "ALARM_TRIGGERED";
export const ALARM_DISABLED = "ALARM_DISABLED";
