#ifndef controller_events_h
#define controller_events_h

#define ACTION_KETTLE_TURN_ON "ACTION_KETTLE_TURN_ON"
#define ACTION_ALARM_ENABLE "ACTION_ALARM_ENABLE"
#define ACTION_ALARM_DISABLE "ACTION_ALARM_DISABLE"

#define UPDATE_KETTLE_TEMP "UPDATE_KETTLE_TEMP"
#define UPDATE_KETTLE_ACTIVE_STATE "UPDATE_KETTLE_ACTIVE_STATE"
#define UPDATE_ALARM_STATE "UPDATE_ALARM_STATE"
#define UPDATE_ROOM_TEMP "UPDATE_ROOM_TEMP"
#define UPDATE_ROOM_HUMIDITY "UPDATE_ROOM_HUMIDITY"

#define REGISTER_CONTROLLER "REGISTER_CONTROLLER"

#endif