#ifndef controller_events_h
#define controller_events_h

#define ACTION_KETTLE_TURN_ON "ACTION_KETTLE_TURN_ON"
#define ACTION_ALARM_ENABLE "ACTION_ALARM_ENABLE"
#define ACTION_ALARM_DISABLE "ACTION_ALARM_DISABLE"

#define UPDATE_KETTLE_TEMP "UPDATE_KETTLE_TEMP"
#define UPDATE_KETTLE_ACTIVE_STATE "UPDATE_KETTLE_ACTIVE_STATE"
#define UPDATE_ALARM_STATE "UPDATE_ALARM_STATE"
#define UPDATE_ROOM_TEMP "UPDATE_ROOM_TEMP"
#define UPDATE_ROOM_HUMIDITY "UPDATE_ROOM_HUMIDITY"

// #define TURN_KETTLE_ON_SUCCESS "TURN_KETTLE_ON_SUCCESS"
#define REGISTER_CONTROLLER "REGISTER_CONTROLLER"
// #define ALARM_TRIGGERED "ALARM_TRIGGERED"
// #define ALARM_DISABLED "ALARM_DISABLED"
// #define SYS_STARTED "SYS_STARTED"
// #define DISABLE_ALARM "DISABLE_ALARM"
// #define START_SYS "START_SYS"
// #define TEMPERATUR_WASSER "TEMPERATUR_WASSER"
// #define TEMPERATUR "TEMPERATUR"
// #define HUMIDITY "HUMIDITY"

#endif