#ifndef controller_events_h
#define controller_events_h

#define TURN_KETTLE_ON "TURN_KETTLE_ON"
#define TURN_KETTLE_ON_SUCCESS "TURN_KETTLE_ON_SUCCESS"
#define REGISTER_CONTROLLER "REGISTER_CONTROLLER"
#define ALARM_TRIGGERED "ALARM_TRIGGERED"
#define ALARM_DISABLED "ALARM_DISABLED"
#define SYS_STARTED "SYS_STARTED"
#define DISABLE_ALARM "DISABLE_ALARM"
#define START_SYS "START_SYS"
#define TEMPERATUR_WASSER "TEMPERATUR_WASSER"
#define TEMPERATUR "TEMPERATUR"
#define HUMIDITY "HUMIDITY"

#endif